Add cuda_test rule
bazel-contrib/rules_cuda pull request #168
Opened 2023-09-17 23:51 UTC by hofbi

Fixes #166

2023-09-18 01:49 UTC, cloudhan commented on MODULE.bazel
> +bazel_dep(name = "rules_cc", version = "0.0.8")
You don't need this.

2023-09-18 01:49 UTC, cloudhan commented on cuda/private/rules/cuda_test.bzl
> +    cc_test(
You can use native.cc_test

2023-09-18 01:50 UTC, cloudhan commented on cuda/private/rules/cuda_test.bzl
Could you move this file to **macros**/cuda_test.bzl?

2023-09-18 05:43 UTC, jsharpe requested changes
Main change required is to pass through kwargs so that all attributes are supported. Can you also make sure that this is documented in the generated docs?

2023-09-18 05:43 UTC, jsharpe commented on cuda/private/macros/cuda_test.bzl
> +        visibility = ["//visibility:private"],
This is not respecting the package level default visibility, this should be unset if not specified.

2023-09-18 05:43 UTC, jsharpe commented on cuda/private/macros/cuda_test.bzl
> +    cuda_library(
Make the visibility of this target private to hide the implementation detail?

2023-09-18 05:43 UTC, jsharpe commented on cuda/private/macros/cuda_test.bzl
> +    )
What about all the other attributes for cc_test? In particular exec_comaptible_with and exec_properties are important for selecting the correct execution platform as the user needs to ensure this is run on a platform that has a cuda compatible GPU present.
The easiest way to do this is to forward kwargs to this rule so you don't have to explicitly list all attributes.

2023-09-18 05:43 UTC, jsharpe commented on cuda/private/macros/cuda_test.bzl
> +def cuda_test(
Can you add a doc string so that the docs can include usage for this macro?

2023-09-18 05:43 UTC, jsharpe commented on cuda/private/macros/cuda_test.bzl
> +    cuda_library(
Also can this target be marked as test only?

2023-09-18 07:19 UTC, cloudhan commented
To enable the docs gen, re-export the symbol like the following:
https://github.com/bazel-contrib/rules_cuda/blob/4c0020c4fa05500d83dd93583fbd12c16d0d1b79/docs/user_docs.bzl#L5-L6

2023-09-19 10:07 UTC, jsharpe reviewed
LGTM - just one last change to propagate tags into the _cuda_library and then I think this is good to go.

2023-09-19 10:07 UTC, jsharpe commented on cuda/private/macros/cuda_test.bzl
> +        deps = getattr(attrs, "deps", []),
I think we also want to propagate tags into the _cuda_library?

2023-09-25 04:54 UTC, merged